apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitops-demo
  name: gitops-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gitops-demo
  type: ClusterIP